org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.caching.debug=false
#org.gradle.configureondemand=true

mod.id=hardcore_disabled_fix
mod.license=MIT
mod.name=Hardcore Disabled Fix
mod.authors="WJiangzhi"
mod.version=0.1-SNAPSHOT1
mod.group=io.github.wjiangzhi.hardcore_disabled_fix
mod.description=A lightweight client-side mod that fixes and restores usability of certain world options when playing in Hardcore mode.
